name: New brain map
description: Request to add brain map
title: "[ENH] Request to add brain map"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "Welcome to `neuromaps-mouse`! We're always happy to add new brain maps to our project. Please fill out the information below and one of the maintainers will get back to you with any questions."
  - type: checkboxes
    id: owner
    attributes:
      label: Brain map source
      description: "What is the source of the brain map(s) you want added to `neuromaps`?"
      options:
        - label: I am sharing a brain map from my own research
        - label: I am requesting a brain map be added from a published article
  - type: checkboxes
    id: open-access
    attributes:
      label: Licensing
      description: "The brain map(s) you are requesting to add to `neuromap-mouse` will be made openly-available under a CC-BY license."
      options:
        - label: I have the necessary permissions to share these brain map(s) under a CC-BY license or they have already been made openly-available under a similar license.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Map description
      description: "Please provide a brief description of the brain map here."
      placeholder: "Where is the brain map from? What brain feature(s) does it describe?"
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Download details
      description: "Where can we find a copy of the brain map(s)?"
      placeholder: "Please include direct links!"
    validations:
      required: true
  - type: input
    id: reference
    attributes:
      label: Reference DOI
      description: "If there is a journal article associated with this brain map, please include the DOI for the article here."
      placeholder: "https://doi.org/..."